const example_1_5_1 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_track" id="]Ar|8{@G:Q:u6N]Xi9C7" x="561" y="129"><value name="TIMBRE"><block type="text" id="]HuWnVu5~K/l7/a]BOiX"><field name="TEXT">piano</field></block></value><value name="TEMPO"><block type="math_number" id="HyFckejpS}[ncuMiGE,e"><field name="NUM">120</field></block></value><value name="VOLUMN"><block type="math_number" id="QF{9xu-b?5Q^`9z[|:{M"><field name="NUM">100</field></block></value><statement name="measures"><block type="create_measure_match_zero_new" id="26znrh6nN9L7@[H-4V:h"><value name="MEASURE"><block type="math_number" id="qWxe=BJXWz8ng00)1BG9"><field name="NUM">1</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">C4</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">0---------------</field></block></value></block></statement></block></xml>';
const example_1_5_2 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_track" id=",:*TKH3,.@,N3v@Osnhw" x="646" y="209"><value name="TIMBRE"><block type="text" id="Q-5%3SxxdboF}|Y}w|A8"><field name="TEXT">piano</field></block></value><value name="TEMPO"><block type="math_number" id="*Cf(n@i5-ehTy_8Z3PQn"><field name="NUM">120</field></block></value><value name="VOLUMN"><block type="math_number" id="h021V,-ih;|0lhk2vqXB"><field name="NUM">100</field></block></value><statement name="measures"><block type="create_measure_match_zero_new" id="bVVP@l5yix?W34miG~Ty"><value name="MEASURE"><block type="math_number" id="f4*s,S6wVB`{ZRwaLzmb"><field name="NUM">1</field></block></value><value name="SEQUENCE"><block type="text" id="0fR:J8hwwJZB|LGorAPC"><field name="TEXT">C4,D4</field></block></value><value name="BEAT"><block type="text" id="~OFxT!wG:%DI9ozTMd15"><field name="TEXT">0-------0-------</field></block></value></block></statement></block></xml>';
const example_1_5_3 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_track" id="]Ar|8{@G:Q:u6N]Xi9C7" x="561" y="129"><value name="TIMBRE"><block type="text" id="]HuWnVu5~K/l7/a]BOiX"><field name="TEXT">piano</field></block></value><value name="TEMPO"><block type="math_number" id="HyFckejpS}[ncuMiGE,e"><field name="NUM">120</field></block></value><value name="VOLUMN"><block type="math_number" id="QF{9xu-b?5Q^`9z[|:{M"><field name="NUM">100</field></block></value><statement name="measures"><block type="create_measure_match_zero_new" id="f8`Kt_$U;WA{%2=vGCAs" x="527" y="68"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">C4,D4,E4,F4</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">0---0---0---0---</field></block></value></block></xml>';
const example_1_5_4 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_track" id="]Ar|8{@G:Q:u6N]Xi9C7" x="561" y="129"><value name="TIMBRE"><block type="text" id="]HuWnVu5~K/l7/a]BOiX"><field name="TEXT">piano</field></block></value><value name="TEMPO"><block type="math_number" id="HyFckejpS}[ncuMiGE,e"><field name="NUM">120</field></block></value><value name="VOLUMN"><block type="math_number" id="QF{9xu-b?5Q^`9z[|:{M"><field name="NUM">100</field></block></value><statement name="measures"><block type="create_measure_match_zero_new" id="f8`Kt_$U;WA{%2=vGCAs" x="527" y="68"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">C4,D4,E4,F4,C4,D4,E4,F4</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">0-0-0-0-0-0-0-0-</field></block></value></block></xml>';
const example_1_5_5 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_track" id="]Ar|8{@G:Q:u6N]Xi9C7" x="561" y="129"><value name="TIMBRE"><block type="text" id="]HuWnVu5~K/l7/a]BOiX"><field name="TEXT">piano</field></block></value><value name="TEMPO"><block type="math_number" id="HyFckejpS}[ncuMiGE,e"><field name="NUM">120</field></block></value><value name="VOLUMN"><block type="math_number" id="QF{9xu-b?5Q^`9z[|:{M"><field name="NUM">100</field></block></value><statement name="measures"><block type="create_measure_match_zero_new" id="f8`Kt_$U;WA{%2=vGCAs" x="527" y="68"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">C5,B4,B4,B4,C5,B4,B4,B4,C5,B4,B4,B4,C5,B4,B4,B4</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">0000000000000000</field></block></value></block></xml>';
const example_1_5_6 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_track" id="]Ar|8{@G:Q:u6N]Xi9C7" x="561" y="129"><value name="TIMBRE"><block type="text" id="]HuWnVu5~K/l7/a]BOiX"><field name="TEXT">piano</field></block></value><value name="TEMPO"><block type="math_number" id="HyFckejpS}[ncuMiGE,e"><field name="NUM">120</field></block></value><value name="VOLUMN"><block type="math_number" id="QF{9xu-b?5Q^`9z[|:{M"><field name="NUM">100</field></block></value><statement name="measures"><block type="create_measure_match_zero_new" id="f8`Kt_$U;WA{%2=vGCAs" x="491" y="40"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">C5,B4,B4,B4,C5,B4,B4,B4,C5,B4,B4,B4,C5,B4,B4,B4,C5,B4,B4,B4,C5,B4,B4,B4,C5,B4,B4,B4,C5,B4,B4,B4</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">00000000000000000000000000000000</field></block></value></block></xml>';

const example_1_17 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_track" id="]Ar|8{@G:Q:u6N]Xi9C7" x="561" y="129"><value name="TIMBRE"><block type="text" id="]HuWnVu5~K/l7/a]BOiX"><field name="TEXT">piano</field></block></value><value name="TEMPO"><block type="math_number" id="HyFckejpS}[ncuMiGE,e"><field name="NUM">120</field></block></value><value name="VOLUMN"><block type="math_number" id="QF{9xu-b?5Q^`9z[|:{M"><field name="NUM">100</field></block></value><statement name="measures"><block type="create_measure_match_zero_new" id="f8`Kt_$U;WA{%2=vGCAs" x="390" y="182"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">C4,C4</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">0--0</field></block></value></block></xml>';
const example_1_23 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_track" id="]Ar|8{@G:Q:u6N]Xi9C7" x="561" y="129"><value name="TIMBRE"><block type="text" id="]HuWnVu5~K/l7/a]BOiX"><field name="TEXT">piano</field></block></value><value name="TEMPO"><block type="math_number" id="HyFckejpS}[ncuMiGE,e"><field name="NUM">120</field></block></value><value name="VOLUMN"><block type="math_number" id="QF{9xu-b?5Q^`9z[|:{M"><field name="NUM">100</field></block></value><statement name="measures"><block type="create_measure_match_zero_new" id="f8`Kt_$U;WA{%2=vGCAs" x="546" y="29"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="TIMBRE"><block type="text" id="1bTJTmzU$8IewRVRPZJU"><field name="TEXT">piano</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">C4,C4,C4,C4,C4,C4</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">0--0--0--000</field></block></value></block></xml>';

export default {
  example_1_5_1,
  example_1_5_2,
  example_1_5_3,
  example_1_5_4,
  example_1_5_5,
  example_1_5_6,
  example_1_17,
  example_1_23
};
